### ISSUE TITLE
Public meetings on Jitsi?

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/did-pkh#10]
can we request `meet.w3c-ccg.org/didpkh` and get it listed on the meetings page once we have a time picked and our `CODEOWNERS` stuff worked out? It might be nice to invite people on the CASA Discord if/whenever topics of CASA importance (or requiring the expertise of a given CAIP author) come up.

**Comment by bumblefudge** [comment]
CODEOWNERS agreed to every other Thursday at 1.30 EST for a half hour starting NEXT thursday (2Dec)

**Comment by bumblefudge** [comment]
Is "Review of outstanding PRs and issue review" as the default agenda, and invite people to open issues if they want to agenda another topic?

**Comment by mprorock** [comment]
Yeah, that should be fine.  let me know:
1) Official Subject/Title for meeting
2) In description: Moderation statement (e.g. rotating through editors, or whatever)
3) general description/standing agenda with links to issues and PRs with desired sorting, etc.

At that point I can drop it on the calendar

**Comment by bumblefudge** [comment]
1. W3C-CCG work item: DID:PKH method 
2. Description:
At least one of three work item owners will moderate PR review and issue review (respectively) at each meeting, with the prioritization of the latter at the discretion of the chairs. Implementers, researchers, and community members are welcome to open issues if they would like clarification of the intended or possible usages of the method. We will use the "next meeting" tag for issues and PRs that we want to discuss soon, so the [next meeting view](https://github.com/w3c-ccg/did-pkh/labels/next%20meeting) is the fastest way to see an up-to-date agenda for the upcoming meetings.

**Comment by bumblefudge** [comment]
closed on today's jitsi call
