### ISSUE TITLE
Debate: how to frame rotation and deletion capabilities

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/did-pkh#11]
There was disagreement among the editors about how to frame the rotation capabilities vis-a-vis the DID method specification template put forth by CCG.  The decision was taken to merge the method specification as-is in #2 but open a new issue to track the conversation.

**Comment by bumblefudge** [comment]
alternate phrasing discussed on call, will be PR'd in.

**Comment by oed** [comment]
What was the alternative phrasing that we planned on using? This is already starting to become an issue in conversations.

**Comment by bumblefudge** [comment]
Lets discuss on the call! I tagged you for review in #19
