### ISSUE TITLE
Create a Universal Resolver driver?

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-pkh#17]
Any plans to contribute a driver for the [DIF Universal Resolver](https://dev.uniresolver.io/)? It's easy, just make a Docker image that wraps one of the existing implementations.

See here: https://github.com/decentralized-identity/universal-resolver/blob/master/docs/driver-development.md

Happy to assist.

**Comment by clehner** [comment]
@peacekeeper it's there already, as part of the DIDKit driver

**Comment by bumblefudge** [comment]
![image](https://user-images.githubusercontent.com/37127325/144494886-1f71dd2d-ec64-421b-b074-5ee52cab01b3.png)
the call is coming from inside the house!
