### ISSUE TITLE
When are did-pkh meetings held, again?

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/did-pkh#32]
The README now says --
> Regular meetings for this CCG work item will be held every four weeks on Wednesdays, from April 20th, 2022, onwards, at [12.15PM Eastern Time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=2022-04-20T12:15:00&p1=179), on a [workitem-specific jitsi room](https://meet.w3c-ccg.org/didpkh) hosted by the CCG. Minutes will be published in [the meetings directory](https://github.com/w3c-ccg/did-pkh/blob/main/meetings) here in the repo.

However, I don't believe we've had a did-pkh meeting since April. What shall we do with this CCG Work Item?

**Comment by bumblefudge** [comment]
closed by #34
