### ISSUE TITLE
Add a specification to the repository

### ISSUE THREAD

**Issue by ukstv** [w3c-ccg/did-pkh#9]
Please, add a text of the specification here. The link leads to a stale version of the spec.

**Comment by oed** [comment]
This is being addressed in https://github.com/w3c-ccg/did-pkh/pull/2

**Comment by bumblefudge** [comment]
#2 closed, but note my [review comment](https://github.com/w3c-ccg/did-pkh/pull/2#pullrequestreview-813820103) -- needs not be final or definitive, any nits or edits can be opened as new issues!
